apiVersion: v1
kind: Service
metadata:
  name: {{ include "varta-web.fullname" . }}
  labels:
    {{- include "varta-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
  selector:
    {{- include "varta-web.selectorLabels" . | nindent 4 }}
